server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: spring-api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: 1
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/askavatar/**
            
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG            